version: 2.1
orbs:
  node: circleci/node@5
  docker: circleci/docker@2.1.4
  heroku: circleci/heroku@2.0.0
  snyk: snyk/snyk@1.5.0

jobs:
  build:
    # Install Node dependencies & cache them
    executor: node/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-modules-{{ checksum "package-lock.json" }}
      - node/install-packages:
          pkg-manager: npm
      - save_cache:
          paths:
            - ./node_modules
          key: node-modules-{{ checksum "package-lock.json" }}

  test:
    # Run Jest tests
    executor: node/default
    environment:
      JEST_JUNIT_OUTPUT_DIR: ./test-results/
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-modules-{{ checksum "package-lock.json" }}
      - run:
          name: Run tests
          command: |
            echo "Running tests"
            npm run test --ci --runInBand --reporters=default --reporters=jest-junit
      - store_test_results:
          path: ./test-results/
      - store_artifacts:
          path: ./test-results/

  scan:
    docker:
      - image: cimg/node:16.10
    environment:
      IMAGE_NAME: clement7903/container-assignment:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Docker Login
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run: docker build -t $IMAGE_NAME .
      - snyk/scan:
          docker-image-name: $IMAGE_NAME

  codescan:
    docker:
      - image: cimg/node:16.10
    environment:
      IMAGE_NAME: clement7903/container-assignment:latest
    steps:
      - checkout
      - setup_remote_docker
      - docker/check
      - run:
          name: Build Docker Image
          command: docker build -t $IMAGE_NAME .
      - snyk/install
      - run:
          name: Run Snyk Code Test
          command: snyk code test

  publish:
    # publish Steps
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login to Docker Hub
          command: |
            echo "Logging in to Docker Hub"
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run:
          name: Build and Push Docker Image
          command: |
            echo "Building and Pushing Docker Image"
            docker build -t container-assignment:latest .
            docker tag container-assignment:latest clement7903/container-assignment:latest
            docker push clement7903/container-assignment:latest
  deploy:
    docker:
      - image: cimg/node:16.10
    steps:
      - setup_remote_docker
      - heroku/install
      - checkout
      - run:
          name: Heroku Container Push
          command: |
            heroku container:login
            heroku stack:set container -a clement-su-devops
            heroku container:push web -a clement-su-devops
            heroku container:release web -a clement-su-devops

workflows:
  build-test-publish:
    jobs:
      - build:
        filters:
          branches:
            only:
              - main
              - release
          tags:
            only: /^v\d+\.\d+\.\d+$/ # Semantic Versioning tags
      - test:
          requires:
            - build
          filters:
            branches:
              only:
                - main
                - release
            tags:
              only: /^v\d+\.\d+\.\d+$/ # Semantic Versioning tags
      - scan:
          requires:
            - build
          context: docker-hub-credentials
          filters:
            branches:
              only: main
      - codescan:
          requires:
            - build
          context: docker-hub-credentials
          filters:
            branches:
              only: main
      - publish:
          requires:
            - test
          context: docker-hub-credentials
          filters:
            branches:
              only:
                - release
            tags:
              only: /^v\d+\.\d+\.\d+$/ # Run on Semantic Versioning tags
      - deploy:
          requires:
            - publish
          filters:
            branches:
              only:
                - release
            tags:
              only: /^v\d+\.\d+\.\d+$/ # Run on Semantic Versioning tags
